import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import { cn } from "@/lib/utils";

const fontTitle = Inter({
    variable: "--font-title",
    subsets: ["latin"],
});

const fontSans = Inter({
    variable: "--font-sans",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Persona AI | Carlos Danyel Silva Teixeira",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-BR">
            <body
                className={cn(
                    "min-h-screen bg-black font-sans antialiased ",
                    fontTitle.variable,
                    fontSans.variable
                )}
            >
                {children}
            </body>
        </html>
    );
}
